### PR TITLE
fix invalid require

### PR DESCRIPTION
**Pull request by yocontra**

### CODE REVIEW

**Comment by YerkoPalma** [comment]
thanks! :v:

**Comment by yocontra** [comment]
@YerkoPalma Thanks - can you publish a new release to NPM?

**Comment by YerkoPalma** [comment]
@contra I'm behind some corporative firewall right now. Will update to npm in a few hours.

**Comment by YerkoPalma** [comment]
📦🎉  `2.0.1`

**Comment by yocontra** [comment]
@YerkoPalma Looks like the file in question isn't included in the package - https://github.com/YerkoPalma/is-valid-identifier/blob/master/package.json#L8 will need to add it to that array and publish a new release.

**Comment by YerkoPalma** [comment]
@contra should be ok now

**Pull request merged**
